### ISSUE TITLE
Flow will not run after updating with a new ActionScope

### ISSUE THREAD

**Issue by DavidKelly-Praedictus** [globus/globus-automate-client#175]
Version: globus-automate 0.16.1.post1

If you update a flow with `globus-automate flow update`, and your update references a new ActionScope, the flow will not run. It will throw this error:
```
{
  "error": {
    "code": "FLOW_INPUT_ERROR",
    "detail": "For RunAs value User, unable to get tokens for scopes {'https://auth.globus.org/scopes/5fac2e64-c734-4e6b-90ea-ff12ddbf9653/notification_notify'}"
  },
  "debug_id": "8991ab0f-05a0-4382-9e7c-5f259cbe5da7"
}
```
I think perhaps this is a bug, and it should ask for the new permissions instead of throwing an error. As a workaround, resetting everything with`globus-automate session logout` and then providing a globus authorization code twice seems to do the trick.

**Comment by kurtmckee** [comment]
Thanks for reporting this David!

The error message from the Flows service is explicit, but still opaque, so there's likely an opportunity to improve that. In addition, the Automate CLI needs to catch that this is happening because it's submitting cached credentials that need to be updated.

I'll make sure this issue is flagged in our unified issue tracker so it can be prioritized to get fixed.
